import AquaglowEco from '@/images/pumps/Aquaglow/AquaglowEco.png';
import AquaglowBoost from '@/images/pumps/Aquaglow/AquaglowBoost.png';
import AquaglowTurbo from '@/images/pumps/Aquaglow/AquaglowTurbo.png';
import AquaglowUltra from '@/images/pumps/Aquaglow/AquaglowUltra.png';
import AquaglowForce from '@/images/pumps/Aquaglow/AquaglowForce.png';

import ZenflowForce from '@/images/pumps/Zenflow/ZenflowForce.png';
import ZenflowTurbo from '@/images/pumps/Zenflow/ZenflowTurbo.png';
import ZenflowEco from '@/images/pumps/Zenflow/ZenflowEco.png';
import ZenflowUltramax from '@/images/pumps/Zenflow/ZenflowUltramax.png';
import ZenflowUltra from '@/images/pumps/Zenflow/ZenflowUltra.png';
import ZenflowBoost from '@/images/pumps/Zenflow/ZenflowBoost.png';
import ZenflowUltramaxPlus from '@/images/pumps/Zenflow/ZenflowUltramaxPlus.png';
import ZenflowUltramaxPro from '@/images/pumps/Zenflow/ZenflowUltramaxPro.png';

import DeepflowBoost from '@/images/pumps/Deepflow/DeepflowBoost.png';
import DeepflowEco from '@/images/pumps/Deepflow/DeepflowEco.png';
import DeepflowEcoMax from '@/images/pumps/Deepflow/DeepflowEcoMax.png';
import DeepflowBoostApex from '@/images/pumps/Deepflow/DeepflowBoostApex.png';
import DeepflowBoostEdge from '@/images/pumps/Deepflow/DeepflowBoostEdge.png';
import DeepflowBoostFlow from '@/images/pumps/Deepflow/DeepflowBoostFlow.png';
import DeepflowBoostLite from '@/images/pumps/Deepflow/DeepflowBoostLite.png';
import DeepflowBoostMax from '@/images/pumps/Deepflow/DeepflowBoostMax.png';
import DeepflowBoostNeo from '@/images/pumps/Deepflow/DeepflowBoostNeo.png';
import DeepflowBoostPlus from '@/images/pumps/Deepflow/DeepflowBoostPlus.png';
import DeepflowBoostPrime from '@/images/pumps/Deepflow/DeepflowBoostPrime.png';
import DeepflowBoostPro from '@/images/pumps/Deepflow/DeepflowBoostPro.png';
import DeepflowBoostUltra from '@/images/pumps/Deepflow/DeepflowBoostUltra.png';
import DeepflowBoostX from '@/images/pumps/Deepflow/DeepflowBoostX.png';
import DeepflowEcoApex from '@/images/pumps/Deepflow/DeepflowEcoApex.png';
import DeepflowEcoEdge from '@/images/pumps/Deepflow/DeepflowEcoEdge.png';
import DeepflowEcoFlow from '@/images/pumps/Deepflow/DeepflowEcoFlow.png';
import DeepflowEcoLite from '@/images/pumps/Deepflow/DeepflowEcoLite.png';
import DeepflowEcoNeo from '@/images/pumps/Deepflow/DeepflowEcoNeo.png';
import DeepflowEcoPlus from '@/images/pumps/Deepflow/DeepflowEcoPlus.png';
import DeepflowEcoPrime from '@/images/pumps/Deepflow/DeepflowEcoPrime.png';
import DeepflowEcoPro from '@/images/pumps/Deepflow/DeepflowEcoPro.png';
import DeepflowEcoUltra from '@/images/pumps/Deepflow/DeepflowEcoUltra.png';
import DeepflowEcoX from '@/images/pumps/Deepflow/DeepflowEcoX.png';

import SludgeproEco from '@/images/pumps/Sludgepro/SludgeproEco.png';
import SludgeproBoost from '@/images/pumps/Sludgepro/SludgeproBoost.png';
import SludgeproBoostFlow from '@/images/pumps/Sludgepro/SludgeproBoostFlow.png';
import SludgeproBoostLite from '@/images/pumps/Sludgepro/SludgeproBoostLite.png';
import SludgeproBoostPlus from '@/images/pumps/Sludgepro/SludgeproBoostPlus.png';
import SludgeproEcoFlow from '@/images/pumps/Sludgepro/SludgeproEcoFlow.png';
import SludgeproEcoLite from '@/images/pumps/Sludgepro/SludgeproEcoLite.png';
import SludgeproEcoPlus from '@/images/pumps/Sludgepro/SludgeproEcoPlus.png';

import StageproUltra from '@/images/pumps/Stagepro/StageproUltra.png';
import StageproEco from '@/images/pumps/Stagepro/StageproEco.png';
import StageproUltramax from '@/images/pumps/Stagepro/StageproUltramax.png';
import StageproBoost from '@/images/pumps/Stagepro/StageproBoost.png';
import StageproElite from '@/images/pumps/Stagepro/StageproElite.png';
import StageproForce from '@/images/pumps/Stagepro/StageproForce.png';
import StageproInfinity from '@/images/pumps/Stagepro/StageproInfinity.png';
import StageproPrime from '@/images/pumps/Stagepro/StageproPrime.png';
import StageproTurbo from '@/images/pumps/Stagepro/StageproTurbo.png';
import StageproUltramaxPlus from '@/images/pumps/Stagepro/StageproUltramaxPlus.png';
import StageproUltramaxPro from '@/images/pumps/Stagepro/StageproUltramaxPro.png';

import MegaflowEco from '@/images/pumps/Megaflow/MegaflowEco.png';
import MegaflowBoost from '@/images/pumps/Megaflow/MegaflowBoost.png';
import MegaflowForce from '@/images/pumps/Megaflow/MegaflowForce.png';
import MegaflowTurbo from '@/images/pumps/Megaflow/MegaflowTurbo.png';
import MegaflowUltra from '@/images/pumps/Megaflow/MegaflowUltra.png';

import FlowmasterTurbo from '@/images/pumps/Flowmaster/FlowmasterTurbo.png';
import FlowmasterBoost from '@/images/pumps/Flowmaster/FlowmasterBoost.png';
import FlowmasterEco from '@/images/pumps/Flowmaster/FlowmasterEco.png';
import FlowmasterUltramaxPlus from '@/images/pumps/Flowmaster/FlowmasterUltramaxPlus.png';
import FlowmasterForce from '@/images/pumps/Flowmaster/FlowmasterForce.png';
import FlowmasterUltramax from '@/images/pumps/Flowmaster/FlowmasterUltramax.png';
import FlowmasterElite from '@/images/pumps/Flowmaster/FlowmasterElite.png';
import FlowmasterInfinity from '@/images/pumps/Flowmaster/FlowmasterInfinity.png';
import FlowmasterOmega from '@/images/pumps/Flowmaster/FlowmasterOmega.png';
import FlowmasterPrime from '@/images/pumps/Flowmaster/FlowmasterPrime.png';
import FlowmasterTitan from '@/images/pumps/Flowmaster/FlowmasterTitan.png';
import FlowmasterUltra from '@/images/pumps/Flowmaster/FlowmasterUltra.png';
import FlowmasterUltramaxPro from '@/images/pumps/Flowmaster/FlowmasterUltramaxPro.png';

import CutmaxxEco from '@/images/pumps/Cutmaxx/CutmaxxEco.png';
import CutmaxxBoost from '@/images/pumps/Cutmaxx/CutmaxxBoost.png';
import CutmaxxBoostFlow from '@/images/pumps/Cutmaxx/CutmaxxBoostFlow.png';
import CutmaxxBoostLite from '@/images/pumps/Cutmaxx/CutmaxxBoostLite.png';
import CutmaxxBoostPlus from '@/images/pumps/Cutmaxx/CutmaxxBoostPlus.png';
import CutmaxxEcoFlow from '@/images/pumps/Cutmaxx/CutmaxxEcoFlow.png';
import CutmaxxEcoLite from '@/images/pumps/Cutmaxx/CutmaxxEcoLite.png';

import AquariseEco from '@/images/pumps/Aquarise/AquariseEco.png';
import AquariseBoost from '@/images/pumps/Aquarise/AquariseBoost.png';

import FlowmaxxEco from '@/images/pumps/Flowmaxx/FlowmaxxEco.png';
import FlowmaxxBoost from '@/images/pumps/Flowmaxx/FlowmaxxBoost.png';
import FlowmaxxTurbo from '@/images/pumps/Flowmaxx/FlowmaxxTurbo.png';
import FlowmaxxForce from '@/images/pumps/Flowmaxx/FlowmaxxForce.png';
import FlowmaxxUltra from '@/images/pumps/Flowmaxx/FlowmaxxUltra.png';

import ShalloproEco from '@/images/pumps/Shallopro/ShalloproEco.png';
import ShalloproBoost from '@/images/pumps/Shallopro/ShalloproBoost.png';

import WellriseTurboLite from '@/images/pumps/Wellrise/WellriseTurboLite.png';
import WellriseEco from '@/images/pumps/Wellrise/WellriseEco.png';
import WellriseTurbo from '@/images/pumps/Wellrise/WellriseTurbo.png';
import WellriseBoost from '@/images/pumps/Wellrise/WellriseBoost.png';
import WellriseBoostFlow from '@/images/pumps/Wellrise/WellriseBoostFlow.png';
import WellriseBoostLite from '@/images/pumps/Wellrise/WellriseBoostLite.png';
import WellriseBoostPlus from '@/images/pumps/Wellrise/WellriseBoostPlus.png';
import WellriseEcoFlow from '@/images/pumps/Wellrise/WellriseEcoFlow.png';
import WellriseEcoLite from '@/images/pumps/Wellrise/WellriseEcoLite.png';
import WellriseTurboFlow from '@/images/pumps/Wellrise/WellriseTurboFlow.png';
import WellriseTurboPlus from '@/images/pumps/Wellrise/WellriseTurboPlus.png';

import PrimemateEco from '@/images/pumps/Primemate/PrimemateEco.png';
import PrimemateBoost from '@/images/pumps/Primemate/PrimemateBoost.png';
import PrimemateTurbo from '@/images/pumps/Primemate/PrimemateTurbo.png';

import SuctionProBoost from '@/images/pumps/Suctionpro/SuctionProBoost.png';
import SuctionProEco from '@/images/pumps/Suctionpro/SuctionProEco.png';

import DrainforceBoost from '@/images/pumps/Drainforce/DrainforceBoost.png';
import DrainforceEco from '@/images/pumps/Drainforce/DrainforceEco.png';
import DrainforceTurbo from '@/images/pumps/Drainforce/DrainforceTurbo.png';

export const allProducts = [
  {
    id: 1,
    name: "Aquaglow Eco",
    category: "Aquaglow",
    isBaseVariant: true,
    imageUrl: AquaglowEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 5366,
    horsePower: 0.3,
    maximumHead: 8,
    maximumDischarge: 120,
    stage: 1,
    headRange: [0, 6],
    applications: ["Domestics", "Gardenings", "Agriculture", "Fountain"]
  },
  {
    id: 2,
    name: "Aquaglow Boost",
    category: "Aquaglow",
    imageUrl: AquaglowBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 21609,
    horsePower: 2,
    maximumHead: 15,
    maximumDischarge: 850,
    stage: 1,
    headRange: [5, 100],
    applications: ["Domestics", "Gardenings", "Agriculture", "Fountain"]
  },
  {
    id: 3,
    name: "Aquaglow Turbo",
    category: "Aquaglow",
    imageUrl: AquaglowTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 23079,
    horsePower: 2,
    maximumHead: 30,
    maximumDischarge: 475,
    stage: 2,
    headRange: [10, 20],
    applications: ["Domestics", "Gardenings", "Agriculture", "Fountain"]
  },
  {
    id: 4,
    name: "Aquaglow Ultra",
    category: "Aquaglow",
    imageUrl: AquaglowUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 33810,
    horsePower: 5,
    maximumHead: 30,
    maximumDischarge: 980,
    stage: 2,
    headRange: [10, 20],
    applications: ["Domestics", "Gardenings", "Agriculture", "Fountain"]
  },
  {
    id: 5,
    name: "Aquaglow Force",
    category: "Aquaglow",
    imageUrl: AquaglowForce,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 23667,
    horsePower: "3 hp",
    maximumHead: "30 mtr",
    maximumDischarge: "690 lpm",
    stage: 2,
    headRange: "10 to 20 mtr",
    applications: ["Domestics", "Gardenings", "Agriculture", "Fountain"]
  },
  {
    id: 6,
    name: "Zenflow Force",
    category: "Zenflow",
    imageUrl: ZenflowForce,
    isFavourite: false,
    quantity: 2,
    isAddedtoCart: false,
    price: 6909,
    horsePower: 1,
    maximumHead: 30,
    maximumDischarge: 160,
    efficiency: 28,
    headRange: [10, 25],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 7,
    name: "Zenflow Turbo",
    category: "Zenflow",
    imageUrl: ZenflowTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: true,
    price: 6174,
    horsePower: 1,
    maximumHead: 28,
    maximumDischarge: 160,
    efficiency: 28,
    headRange: [10, 24],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 8,
    name: "Zenflow Eco",
    category: "Zenflow",
    isBaseVariant: true,
    imageUrl: ZenflowEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 5366,
    horsePower: 0.5,
    maximumHead: 24,
    maximumDischarge: 120,
    efficiency: 28,
    headRange: [10, 18],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 9,
    name: "Zenflow Ultramax",
    category: "Zenflow",
    imageUrl: ZenflowUltramax,
    isFavourite: true,
    quantity: 3,
    isAddedtoCart: false,
    price: 7644,
    horsePower: 1,
    maximumHead: 33,
    maximumDischarge: 165,
    efficiency: 28,
    headRange: [15, 28],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 10,
    name: "Zenflow Ultra",
    category: "Zenflow",
    imageUrl: ZenflowUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 6909,
    horsePower: 1,
    maximumHead: 30,
    maximumDischarge: 165,
    efficiency: 28,
    headRange: [10, 25],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 11,
    name: "Zenflow boost",
    category: "Zenflow",
    imageUrl: ZenflowBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 5954,
    horsePower: 0.5,
    maximumHead: 26,
    maximumDischarge: 150,
    efficiency: 28,
    headRange: [10, 22],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 12,
    name: "Zenflow Ultramax Plus",
    category: "Zenflow",
    imageUrl: ZenflowUltramaxPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8379,
    horsePower: 1,
    maximumHead: 36,
    maximumDischarge: 170,
    efficiency: 28,
    headRange: [15, 32],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 13,
    name: "Zenflow Ultramax Pro",
    category: "Zenflow",
    imageUrl: ZenflowUltramaxPro,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8747,
    horsePower: 1.5,
    maximumHead: 38,
    maximumDischarge: 170,
    efficiency: 28,
    headRange: [20, 34],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 14,
    name: "Deepflow Boost",
    category: "Deepflow",
    imageUrl: DeepflowBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 11319,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 15,
    name: "Deepflow Eco",
    category: "Deepflow",
    imageUrl: DeepflowEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 11466,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Borewells"]
  },
  {
    id: 16,
    name: "Deepflow Eco Max",
    category: "Deepflow",
    imageUrl: DeepflowEcoMax,
    isFavourite: true,
    quantity: 1,
    isAddedtoCart: true,
    price: 12936,
    horsePower: 1.5,
    maximumHead: 140,
    maximumDischarge: 80,
    stage: 18,
    headRange: [81, 117],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 17,
    name: "Deepflow Boost Apex",
    category: "Deepflow",
    imageUrl: DeepflowBoostApex,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13083,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 18,
    name: "Deepflow Boost Edge",
    category: "Deepflow",
    imageUrl: DeepflowBoostEdge,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13524,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 19,
    name: "Deepflow Boost Flow",
    category: "Deepflow",
    imageUrl: DeepflowBoostFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 9996,
    horsePower: 1,
    maximumHead: 110,
    maximumDischarge: 80,
    stage: 14,
    headRange: [50, 90],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Borewells"]
  },
  {
    id: 20,
    name: "Deepflow Boost Lite",
    category: "Deepflow",
    imageUrl: DeepflowBoostLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 10290,
    horsePower: 1,
    maximumHead: 90,
    maximumDischarge: 80,
    stage: 12,
    headRange: [54, 78],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Borewells"]
  },
  {
    id: 21,
    name: "Deepflow Boost Max",
    category: "Deepflow",
    imageUrl: DeepflowBoostMax,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 11613,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 22,
    name: "Deepflow Boost Neo",
    category: "Deepflow",
    imageUrl: DeepflowBoostNeo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13083,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 23,
    name: "Deepflow Boost Plus",
    category: "Deepflow",
    imageUrl: DeepflowBoostPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13524,
    horsePower: 1.5,
    maximumHead: 110,
    maximumDischarge: 120,
    stage: 14,
    headRange: [50, 90],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Borewells"]
  },
  {
    id: 24,
    name: "Deepflow Boost Prime",
    category: "Deepflow",
    imageUrl: DeepflowBoostPrime,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 14259,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 25,
    name: "Deepflow Boost Pro",
    category: "Deepflow",
    imageUrl: DeepflowBoostPro,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 17934,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 26,
    name: "Deepflow Boost Ultra",
    category: "Deepflow",
    imageUrl: DeepflowBoostUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 12936,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 27,
    name: "Deepflow Boost X",
    category: "Deepflow",
    imageUrl: DeepflowBoostX,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13100,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [40, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 28,
    name: "Deepflow Eco Apex",
    category: "Deepflow",
    imageUrl: DeepflowEcoApex,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 15900,
    horsePower: 2,
    maximumHead: 130,
    maximumDischarge: 80,
    stage: 20,
    headRange: [60, 100],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 29,
    name: "Deepflow Eco Edge",
    category: "Deepflow",
    imageUrl: DeepflowEcoEdge,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 16170,
    horsePower: 1.5,
    maximumHead: 110,
    maximumDischarge: 65,
    stage: 20,
    headRange: [60, 100],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 30,
    name: "Deepflow Eco Flow",
    category: "Deepflow",
    imageUrl: DeepflowEcoFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 16317,
    horsePower: 1.5,
    maximumHead: 110,
    maximumDischarge: 120,
    stage: 14,
    headRange: [50, 90],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Borewells"]
  },
  {
    id: 31,
    name: "Deepflow Eco Lite",
    category: "Deepflow",
    imageUrl: DeepflowEcoLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 16905,
    horsePower: 1,
    maximumHead: 90,
    maximumDischarge: 80,
    stage: 12,
    headRange: [54, 78],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Borewells"]
  },
  {
    id: 32,
    name: "Deepflow Eco Neo",
    category: "Deepflow",
    imageUrl: DeepflowEcoNeo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 19850,
    horsePower: 1.5,
    maximumHead: 140,
    maximumDischarge: 65,
    stage: 25,
    headRange: [65, 110],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 33,
    name: "Deepflow Eco Plus",
    category: "Deepflow",
    imageUrl: DeepflowEcoPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 20286,
    horsePower: 1.5,
    maximumHead: 120,
    maximumDischarge: 120,
    stage: 15,
    headRange: [67, 97],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 34,
    name: "Deepflow Eco Prime",
    category: "Deepflow",
    imageUrl: DeepflowEcoPrime,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 21462,
    horsePower: 1.5,
    maximumHead: 117,
    maximumDischarge: 80,
    stage: 18,
    headRange: [54, 90],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 35,
    name: "Deepflow Eco Pro",
    category: "Deepflow",
    imageUrl: DeepflowEcoPro,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 22491,
    horsePower: 1,
    maximumHead: 65,
    maximumDischarge: 77,
    stage: 10,
    headRange: [30, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 36,
    name: "Deepflow Eco Ultra",
    category: "Deepflow",
    imageUrl: DeepflowEcoUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 22785,
    horsePower: 1,
    maximumHead: 80,
    maximumDischarge: 80,
    stage: 12,
    headRange: [36, 60],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 37,
    name: "Deepflow Eco X",
    category: "Deepflow",
    imageUrl: DeepflowEcoX,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 24500,
    horsePower: 1.5,
    maximumHead: 100,
    maximumDischarge: 80,
    stage: 15,
    headRange: [45, 75],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 38,
    name: "Sludgepro Eco",
    category: "Sludgepro",
    imageUrl: SludgeproEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 14553,
    horsePower: 1,
    maximumHead: 12,
    maximumDischarge: 360,
    headRange: [3, 9],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
  {
    id: 39,
    name: "Sludgepro Boost",
    category: "Sludgepro",
    imageUrl: SludgeproBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 15729,
    horsePower: 3,
    maximumHead: 23,
    maximumDischarge: 800,
    headRange: [8, 19],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 40,
    name: "Sludgepro Boost Flow",
    category: "Sludgepro",
    imageUrl: SludgeproBoostFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 17493,
    horsePower: 7.5,
    maximumHead: 30,
    maximumDischarge: 160,
    headRange: [15, 26],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 41,
    name: "Sludgepro Boost Lite",
    category: "Sludgepro",
    imageUrl: SludgeproBoostLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 18963,
    horsePower: 5,
    maximumHead: 27,
    maximumDischarge: 950,
    headRange: [15, 24],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 42,
    name: "Sludgepro Boost Plus",
    category: "Sludgepro",
    imageUrl: SludgeproBoostPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 47745,
    horsePower: 10,
    maximumHead: 32,
    maximumDischarge: 1200,
    headRange: [18, 28],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 43,
    name: "Sludgepro Eco Flow",
    category: "Sludgepro",
    imageUrl: SludgeproEcoFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 69480,
    horsePower: 2,
    maximumHead: 16,
    maximumDischarge: 445,
    headRange: [5, 13],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
  {
    id: 44,
    name: "Sludgepro Eco Lite",
    category: "Sludgepro",
    imageUrl: SludgeproEcoLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 84625,
    horsePower: 1.5,
    maximumHead: 14,
    maximumDischarge: 410,
    headRange: [3, 11],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
  {
    id: 45,
    name: "Sludgepro Eco Plus",
    category: "Sludgepro",
    imageUrl: SludgeproEcoPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 110300,
    horsePower: 3,
    maximumHead: 18,
    maximumDischarge: 460,
    headRange: [5, 15],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
  {
    id: 46,
    name: "Stagepro Ultra",
    category: "Stagepro",
    imageUrl: StageproUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 16905,
    horsePower: 2,
    maximumHead: 125,
    maximumDischarge: 90,
    stage: 16,
    headRange: [40, 105],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant"]
  },
  {
    id: 47,
    name: "Stagepro Eco",
    category: "Stagepro",
    imageUrl: StageproEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8967,
    horsePower: 0.5,
    maximumHead: 42,
    maximumDischarge: 120,
    stage: 5,
    headRange: [20, 35],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant"]
  },
  {
    id: 48,
    name: "Stagepro Ultramax",
    category: "Stagepro",
    imageUrl: StageproUltramax,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 25137,
    horsePower: 2,
    maximumHead: 40,
    maximumDischarge: 340,
    stage: 3,
    headRange: [15, 30],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "Industries"]
  },
  {
    id: 49,
    name: "Stagepro Boost",
    category: "Stagepro",
    imageUrl: StageproBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 9996,
    horsePower: 1,
    maximumHead: 57,
    maximumDischarge: 120,
    stage: 7,
    headRange: [30, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant"]
  },
  {
    id: 50,
    name: "Stagepro Elite",
    category: "Stagepro",
    imageUrl: StageproElite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 27195,
    horsePower: 3,
    maximumHead: 67,
    maximumDischarge: 300,
    stage: 5,
    headRange: [25, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "Industries"]
  },
  {
    id: 51,
    name: "Stagepro Force",
    category: "Stagepro",
    imageUrl: StageproForce,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 10437,
    horsePower: 2,
    maximumHead: 110,
    maximumDischarge: 120,
    stage: 14,
    headRange: [40, 90],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "High Rise Building"]
  },
  {
    id: 52,
    name: "Stagepro Infinity",
    category: "Stagepro",
    imageUrl: StageproInfinity,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 38808,
    horsePower: 5,
    maximumHead: 80,
    maximumDischarge: 290,
    stage: 6,
    headRange: [35, 60],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "Industries"]
  },
  {
    id: 53,
    name: "Stagepro prime",
    category: "Stagepro",
    imageUrl: StageproPrime,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 36162,
    horsePower: 5,
    maximumHead: 55,
    maximumDischarge: 490,
    stage: 4,
    headRange: [20, 40],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "Industries"]
  },
  {
    id: 54,
    name: "Stagepro Turbo",
    category: "Stagepro",
    imageUrl: StageproTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 16170,
    horsePower: 1.5,
    maximumHead: 72,
    maximumDischarge: 120,
    stage: 9,
    headRange: [35, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "High Rise Building"]
  },
  {
    id: 55,
    name: "Stagepro Ultramax Plus",
    category: "Stagepro",
    imageUrl: StageproUltramaxPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 24843,
    horsePower: 2,
    maximumHead: 55,
    maximumDischarge: 340,
    stage: 4,
    headRange: [20, 40],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "Industries"]
  },
  {
    id: 56,
    name: "Stagepro Ultramax Pro",
    category: "Stagepro",
    imageUrl: StageproUltramaxPro,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 25431,
    horsePower: 3,
    maximumHead: 40,
    maximumDischarge: 390,
    stage: 3,
    headRange: [15, 30],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Ro Plant", "Industries"]
  },
  {
    id: 57,
    name: "Megaflow Eco",
    category: "Megaflow",
    imageUrl: MegaflowEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 0.5,
    maximumHead: 26,
    maximumDischarge: 150,
    efficiency: 28,
    headRange: [10, 22],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 58,
    name: "Megaflow Boost",
    category: "Megaflow",
    imageUrl: MegaflowBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 7203,
    horsePower: 1,
    maximumHead: 30,
    maximumDischarge: 165,
    efficiency: 28,
    headRange: [10, 25],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 59,
    name: "Megaflow Force",
    category: "Megaflow",
    imageUrl: MegaflowForce,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1,
    maximumHead: 36,
    maximumDischarge: 170,
    efficiency: 28,
    headRange: [15, 32],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 60,
    name: "Megaflow Turbo",
    category: "Megaflow",
    imageUrl: MegaflowTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1,
    maximumHead: 33,
    maximumDischarge: 165,
    efficiency: 28,
    headRange: [15, 28],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 61,
    name: "Megaflow Ultra",
    category: "Megaflow",
    imageUrl: MegaflowUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 7350,
    horsePower: 1.5,
    maximumHead: 38,
    maximumDischarge: 170,
    efficiency: 28,
    headRange: [20, 34],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture"]
  },
  {
    id: 62,
    name: "Flowmaster Turbo",
    category: "Flowmaster",
    imageUrl: FlowmasterTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 5219,
    horsePower: 1,
    maximumHead: 24,
    maximumDischarge: 105,
    headRange: [12, 22],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 63,
    name: "Flowmaster Boost",
    category: "Flowmaster",
    imageUrl: FlowmasterBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 4300,
    horsePower: 0.5,
    maximumHead: 22,
    maximumDischarge: 95,
    headRange: [10, 18],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 64,
    name: "Flowmaster Eco",
    category: "Flowmaster",
    imageUrl: FlowmasterEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 4079,
    horsePower: 0.5,
    maximumHead: 18,
    maximumDischarge: 87,
    headRange: [10, 15],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 65,
    name: "Flowmaster Ultramax Plus",
    category: "Flowmaster",
    imageUrl: FlowmasterUltramaxPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 9849,
    horsePower: 1,
    maximumHead: 20,
    maximumDischarge: 320,
    headRange: [8, 16],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 66,
    name: "Flowmaster Force",
    category: "Flowmaster",
    imageUrl: FlowmasterForce,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 7203,
    horsePower: 1,
    maximumHead: 33,
    maximumDischarge: 120,
    headRange: [15, 28],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 67,
    name: "Flowmaster Ultramax",
    category: "Flowmaster",
    imageUrl: FlowmasterUltramax,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 7019,
    horsePower: 0.5,
    maximumHead: 13,
    maximumDischarge: 300,
    headRange: [5, 12],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 68,
    name: "Flowmaster Elite",
    category: "Flowmaster",
    imageUrl: FlowmasterElite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 12422,
    horsePower: 1.5,
    maximumHead: 22,
    maximumDischarge: 450,
    headRange: [8, 17],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 69,
    name: "Flowmaster Infinity",
    category: "Flowmaster",
    imageUrl: FlowmasterInfinity,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13451,
    horsePower: 2,
    maximumHead: 24,
    maximumDischarge: 525,
    headRange: [14, 22],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 70,
    name: "Flowmaster Omega",
    category: "Flowmaster",
    imageUrl: FlowmasterOmega,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 14480,
    horsePower: 2,
    maximumHead: 18,
    maximumDischarge: 80,
    headRange: [8, 15],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 71,
    name: "Flowmaster Prime",
    category: "Flowmaster",
    imageUrl: FlowmasterPrime,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 12752,
    horsePower: 1.5,
    maximumHead: 18,
    maximumDischarge: 480,
    headRange: [8, 15],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 72,
    name: "Flowmaster Titan",
    category: "Flowmaster",
    imageUrl: FlowmasterTitan,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 13451,
    horsePower: 2,
    maximumHead: 20,
    maximumDischarge: 580,
    headRange: [8, 16],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 73,
    name: "Flowmaster Ultra",
    category: "Flowmaster",
    imageUrl: FlowmasterUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 7203,
    horsePower: 1,
    maximumHead: 30,
    maximumDischarge: 130,
    headRange: [15, 26],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 74,
    name: "Flowmaster Ultramax Pro",
    category: "Flowmaster",
    imageUrl: FlowmasterUltramaxPro,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 10143,
    horsePower: 1,
    maximumHead: 15,
    maximumDischarge: 390,
    headRange: [5, 12],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 75,
    name: "Cutmaxx Eco",
    category: "Cutmaxx",
    imageUrl: CutmaxxEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1.5,
    maximumHead: 12,
    maximumDischarge: 320,
    headRange: [3, 10],
    applications: ["Domestics", "Gardenings", "Drainage", "Stp Plant", "Hotels", "Hospitals"]
  },
  {
    id: 76,
    name: "Cutmaxx Boost",
    category: "Cutmaxx",
    imageUrl: CutmaxxBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 3,
    maximumHead: 23,
    maximumDischarge: 80,
    headRange: [8, 19],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 77,
    name: "Cutmaxx Boost Flow",
    category: "Cutmaxx",
    imageUrl: CutmaxxBoostFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 7.5,
    maximumHead: 30,
    maximumDischarge: 1060,
    headRange: [15, 26],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 78,
    name: "Cutmaxx Boost Lite",
    category: "Cutmaxx",
    imageUrl: CutmaxxBoostLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 5,
    maximumHead: 27,
    maximumDischarge: 950,
    headRange: [15, 24],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 79,
    name: "Cutmaxx Boost Plus",
    category: "Cutmaxx",
    imageUrl: CutmaxxBoostPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 10,
    maximumHead: 32,
    maximumDischarge: 1200,
    headRange: [18, 28],
    applications: ["Dyeing Company", "Municipal Waste Watersystems", "Industries"]
  },
  {
    id: 80,
    name: "Cutmaxx Eco Flow",
    category: "Cutmaxx",
    imageUrl: CutmaxxEcoFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 3,
    maximumHead: 16,
    maximumDischarge: 410,
    headRange: [5, 13],
    applications: ["Domestics", "Gardenings", "Drainage", "Stp Plant", "Hotels", "Hospitals"]
  },
  {
    id: 81,
    name: "Cutmaxx Eco Lite",
    category: "Cutmaxx",
    imageUrl: CutmaxxEcoLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 2,
    maximumHead: 14,
    maximumDischarge: 380,
    headRange: [5, 12],
    applications: ["Domestics", "Gardenings", "Drainage", "Stp Plant", "Hotels", "Hospitals"]
  },
  {
    id: 82,
    name: "Aquarise Eco",
    category: "Aquarise",
    imageUrl: AquariseEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1,
    maximumHead: 30,
    maximumDischarge: 165,
    efficiency: 28,
    headRange: [10, 25],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Solar"]
  },
  {
    id: 83,
    name: "Aquarise Boost",
    category: "Aquarise",
    imageUrl: AquariseBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1,
    maximumHead: 33,
    maximumDischarge: 165,
    efficiency: 28,
    headRange: [15, 28],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "Solar"]
  },
  {
    id: 84,
    name: "Flowmaxx Eco",
    category: "Flowmaxx",
    imageUrl: FlowmaxxEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8269
  },
  {
    id: 85,
    name: "Flowmaxx Boost",
    category: "Flowmaxx",
    imageUrl: FlowmaxxBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8636
  },
  {
    id: 86,
    name: "Flowmaxx Turbo",
    category: "Flowmaxx",
    imageUrl: FlowmaxxTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 11943
  },
  {
    id: 87,
    name: "Flowmaxx Force",
    category: "Flowmaxx",
    imageUrl: FlowmaxxForce,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 11392
  },
  {
    id: 88,
    name: "Flowmaxx Ultra",
    category: "Flowmaxx",
    imageUrl: FlowmaxxUltra,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 14700
  },
  {
    id: 89,
    name: "Shallopro Eco",
    category: "Shallopro",
    imageUrl: ShalloproEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 5880,
    horsePower: 0.5,
    maximumHead: 35,
    maximumDischarge: 52,
    suctionLiftInMtrs: 9,
    headRange: [10, 25],
    applications: ["Domestic", "Small Irrigation", "Shallowell"]
  },
  {
    id: 90,
    name: "Shallopro Boost",
    category: "Shallopro",
    imageUrl: ShalloproBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 6468,
    horsePower: 1.0,
    maximumHead: 45,
    maximumDischarge: 55,
    suctionLiftInMtrs: 9,
    headRange: [20, 40],
    applications: ["Domestic", "Small Irrigation", "Shallowell"]
  },
  {
    id: 91,
    name: "Wellrise Turbo Lite",
    category: "Wellrise",
    imageUrl: WellriseTurboLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 28077,
    horsePower: 3,
    maximumHead: 67,
    maximumDischarge: 300,
    stage: 5,
    headRange: [25, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 92,
    name: "Wellrise Eco",
    category: "Wellrise",
    imageUrl: WellriseEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8453,
    horsePower: 0.5,
    maximumHead: 48,
    maximumDischarge: 120,
    stage: 6,
    headRange: [25, 40],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 93,
    name: "Wellrise Turbo",
    category: "Wellrise",
    imageUrl: WellriseTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 25725,
    horsePower: 2,
    maximumHead: 68,
    maximumDischarge: 250,
    stage: 5,
    headRange: [25, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 94,
    name: "Wellrise Boost",
    category: "Wellrise",
    imageUrl: WellriseBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 8967,
    horsePower: 0.5,
    maximumHead: 40,
    maximumDischarge: 120,
    stage: 5,
    headRange: [20, 35],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 95,
    name: "Wellrise Boost Flow",
    category: "Wellrise",
    imageUrl: WellriseBoostFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 10437,
    horsePower: 1.5,
    maximumHead: 72,
    maximumDischarge: 120,
    stage: 9,
    headRange: [35, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 96,
    name: "Wellrise Boost Lite",
    category: "Wellrise",
    imageUrl: WellriseBoostLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 9996,
    horsePower: 1,
    maximumHead: 56,
    maximumDischarge: 21,
    stage: 7,
    headRange: [30, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 97,
    name: "Wellrise Boost Plus",
    category: "Wellrise",
    imageUrl: WellriseBoostPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 15435,
    horsePower: 2,
    maximumHead: 110,
    maximumDischarge: 120,
    stage: 14,
    headRange: [40, 90],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 98,
    name: "Wellrise Eco Flow",
    category: "Wellrise",
    imageUrl: WellriseEcoFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 10805,
    horsePower: 1.5,
    maximumHead: 80,
    maximumDischarge: 120,
    stage: 10,
    headRange: [35, 65],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 99,
    name: "Wellrise Eco Lite",
    category: "Wellrise",
    imageUrl: WellriseEcoLite,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 9555,
    horsePower: 1,
    maximumHead: 65,
    maximumDischarge: 120,
    stage: 8,
    headRange: [30, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 100,
    name: "Wellrise Turbo Flow",
    category: "Wellrise",
    imageUrl: WellriseTurboFlow,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 28665,
    horsePower: 3,
    maximumHead: 95,
    maximumDischarge: 200,
    stage: 7,
    headRange: [30, 70],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 101,
    name: "Wellrise Turbo Plus",
    category: "Wellrise",
    imageUrl: WellriseTurboPlus,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 37338,
    horsePower: 5,
    maximumHead: 68,
    maximumDischarge: 165,
    stage: 5,
    headRange: [25, 50],
    applications: ["Domestics", "Constructions", "Gardenings", "Agriculture", "High Rise Building"]
  },
  {
    id: 102,
    name: "Primemate Eco",
    category: "Primemate",
    imageUrl: PrimemateEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 3234,
    horsePower: 0.5,
    maximumHead: 30,
    maximumDischarge: 45,
    headRange: [10, 24],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 103,
    name: "Primemate Boost",
    category: "Primemate",
    imageUrl: PrimemateBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 3602,
    horsePower: 0.5,
    maximumHead: 34,
    maximumDischarge: 45,
    headRange: [10, 26],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 104,
    name: "Primemate Turbo",
    category: "Primemate",
    imageUrl: PrimemateTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 4484,
    horsePower: 1,
    maximumHead: 48,
    maximumDischarge: 55,
    headRange: [15, 35],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 105,
    name: "Suction Pro Boost",
    category: "Suction Pro",
    imageUrl: SuctionProBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 5733,
    horsePower: 1,
    maximumHead: 44,
    maximumDischarge: 60,
    headRange: [15, 25],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 106,
    name: "Suction Pro Eco",
    category: "Suction Pro",
    imageUrl: SuctionProEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 4778,
    horsePower: 0.5,
    maximumHead: 35,
    maximumDischarge: 50,
    headRange: [10, 24],
    applications: ["Domestic", "Small Irrigation", "Industries"]
  },
  {
    id: 107,
    name: "Drainforce Boost",
    category: "Drainforce",
    imageUrl: DrainforceBoost,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1.5,
    maximumHead: 14,
    maximumDischarge: 390,
    headRange: [3, 11],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
  {
    id: 108,
    name: "Drainforce Eco",
    category: "Drainforce",
    imageUrl: DrainforceEco,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 1,
    maximumHead: 12,
    maximumDischarge: 340,
    headRange: [3, 9],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
  {
    id: 109,
    name: "Drainforce Turbo",
    category: "Drainforce",
    imageUrl: DrainforceTurbo,
    isFavourite: false,
    quantity: 1,
    isAddedtoCart: false,
    price: 0,
    horsePower: 2,
    maximumHead: 16,
    maximumDischarge: 425,
    headRange: [5, 13],
    applications: ["Domestics", "Constructions", "Gardenings", "Drainage", "Dewatering"]
  },
];